CREATE TABLE MASTER_TABLE (
    ACCOUNT_ID VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(100),
    BALANCE NUMBER(12,2),
    TRANSACTION_TYPE VARCHAR2(20),
    TRANSACTION_DATE DATE,
    SOURCE VARCHAR2(50),
    REMARKS VARCHAR2(255)
);
